---
# ----------------------------------------------------------------------------------------
# -- Docs: https://github.com/cluster-apps-on-docker/spark-standalone-cluster-on-docker --
# ----------------------------------------------------------------------------------------
version: "3.6"



services:


    rabbitmq:
        image: rabbitmq:3.8-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER
            - RABBITMQ_DEFAULT_PASS
        ports:
            # AMQP protocol port
            - "${RABBITMQ_DEFAULT_PORT}:${RABBITMQ_DEFAULT_PORT}"
            # HTTP management UI
            - "${RABBITMQ_DEFAULT_MGMT}:${RABBITMQ_DEFAULT_MGMT}"

    mongo:
        image: mongodb
        volumes:
            - ./db/mongo-data:/data/db
            - ./db/mongo-app:/var/www/html
            - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
        ports:
            - "${MONGODB_PORT}:${MONGODB_PORT}"
        environment:
            - MONGO_INITDB_ROOT_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD
            - MONGODB_PORT
            - DROP_EXISTING
            - WRITE_CASES

    dbinit:
        image: dbinit
        build:
            context: ./dbinit
            dockerfile: Dockerfile
        environment:
            - MONGO_INITDB_ROOT_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD
            - MONGODB_PORT
            - DROP_EXISTING
            - WRITE_CASES
        depends_on:
            - mongo

    web:
        image: web
        build:
            context: ./web
            dockerfile: Dockerfile
        environment:
            - APISERV_PORT

    nginx_rproxy:
        image: nginx_rproxy
        build: ./nginx_rproxy
        ports:
            - "${NGINX_PORT}:${NGINX_PORT}"
        depends_on:
            - web
        

    worker:
        image: worker
        build:
            context: ./worker
            dockerfile: Dockerfile
        depends_on:
            - rabbitmq
            - mongo
        environment:
            - RABBITMQ_DEFAULT_USER
            - RABBITMQ_DEFAULT_PASS
            - RABBITMQ_DEFAULT_PORT
            - MONGO_INITDB_ROOT_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD
            - MONGODB_PORT


    apiserv:
        image: apiserv
        build:
            context: ./apiserv
            dockerfile: Dockerfile
        ports:
            - "${APISERV_PORT}:${APISERV_PORT}"
        depends_on:
            - worker
            - mongo
        environment:
            - RABBITMQ_DEFAULT_USER
            - RABBITMQ_DEFAULT_PASS
            - RABBITMQ_DEFAULT_PORT
            - MONGO_INITDB_ROOT_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD
            - MONGODB_PORT
            - REFCODE_LENGTH




...
