---
# ----------------------------------------------------------------------------------------
# -- Docs: https://github.com/cluster-apps-on-docker/spark-standalone-cluster-on-docker --
# ----------------------------------------------------------------------------------------
version: "3.6"



services:

    web:
        image: web
        restart: always
        build:
            context: ./web
            dockerfile: Dockerfile
        ports:
            - '8501:8501'

    nginx:
        image: nginx_rproxy
        restart: always
        build: ./nginx_rproxy
        ports:
            - "80:80"
        depends_on:
            - web


    worker:
        image: worker
        restart: always
        build:
            context: ./worker
            dockerfile: Dockerfile

    rabbitmq:
        image: rabbitmq:3.8-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=waccproject
            - RABBITMQ_DEFAULT_PASS=waccpassword
        ports:
            # AMQP protocol port
            - '25672:25672'
            # HTTP management UI
            - '15672:15672'
    py-mongo:
        image: mongodb
        build:
            context: ./db
            dockerfile: Dockerfile
        volumes:
            - ./db/mongo-data:/data/db
            - ./db/mongo-app:/var/www/html
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=1234
...
