---
# ----------------------------------------------------------------------------------------
# -- Docs: https://github.com/cluster-apps-on-docker/spark-standalone-cluster-on-docker --
# ----------------------------------------------------------------------------------------
version: "3.6"



services:

    frontend:
        image: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - '8501:8501'

    nginx:
        image: nginx_rproxy
        restart: always
        build: ./nginx_rproxy
        ports:
            - "80:80"
        depends_on:
            - frontend


    backend:
        image: backend
        build:
            context: ./backend
            dockerfile: Dockerfile

    rabbitmq:
        image: rabbitmq:3.8-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=waccproject
            - RABBITMQ_DEFAULT_PASS=waccpassword
        ports:
            # AMQP protocol port
            - '5672:5672'
            # HTTP management UI
            - '15672:15672'

...
