---
# ----------------------------------------------------------------------------------------
# -- Docs: https://github.com/cluster-apps-on-docker/spark-standalone-cluster-on-docker --
# ----------------------------------------------------------------------------------------
version: "3.6"



services:

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: frontend
        ports:
            - '8501:8501'

    nginx:
        container_name: nginx
        restart: always
        build: ./nginx
        ports:
            - "80:80"
        depends_on:
            - frontend


    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3.8-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=waccproject
            - RABBITMQ_DEFAULT_PASS=waccpassword
        ports:
            # AMQP protocol port
            - '5672:5672'
            # HTTP management UI
            - '15672:15672'

...
